### ISSUE TITLE
How to modify an http response

### ISSUE THREAD

**Issue by vizor21** [tetratelabs/getenvoy#108]
I'm trying to modifying an http response in my http filter on_http_response_body method.  Can you suggest how to do that?
Thanks

**Comment by dio** [comment]
Sorry that probably this won't answer your question directly. I assume you're implementing your own HTTP Filter using our [`envoy-wasm-rust-sdk`](https://github.com/tetratelabs/envoy-wasm-rust-sdk). Given you have your own `on_response_body` in your filter. I think currently we don't have something like 'set_response_data' in [`ResponseBodyOps`](https://github.com/tetratelabs/envoy-wasm-rust-sdk/blob/97ef1839b50c620fbc8a09a95965d9d8658b0a49/envoy-sdk/src/extension/filter/http/ops.rs#L97-L101), which probably can be implemented by wrapping [`set_buffer`]( https://github.com/proxy-wasm/proxy-wasm-rust-sdk/blob/4cb2db7e398fb8166f49fcc899ef5ede261005d1/src/hostcalls.rs#L140). We will take a look if setting buffer does make sense. And probably this is a relevant issue for [`envoy-wasm-rust-sdk`](https://github.com/tetratelabs/envoy-wasm-rust-sdk). CMIIW @yskopets. 

FWIW, in Envoy we have Lua API to set response buffer in response path, so I think this is possible and does make sense if we implement such API in the [`envoy-wasm-rust-sdk`](https://github.com/tetratelabs/envoy-wasm-rust-sdk) too.

**Comment by codefromthecrypt** [comment]
closing as this is stale, but please follow-up if not
