### ISSUE TITLE
Can we have ARM64 binary support please?

### ISSUE THREAD

**Issue by lhaig** [tetratelabs/getenvoy#109]
#Environment

## Hardware 
TuringPi Cluster with Raspberry PI 3+ compute modules.
## Software 
Ubuntu 18.04 and 20.04
## Error

curl -L https://getenvoy.io/cli | sudo bash -s -- -b /usr/local/bin
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    93  100    93    0     0    123      0 --:--:-- --:--:-- --:--:--   123
100  9995  100  9995    0     0  11383      0 --:--:-- --:--:-- --:--:-- 11383
tetratelabs/getenvoy crit platform linux/arm64 is not supported.  Make sure this script is up-to-date and file request at https://github.com/tetratelabs/getenvoy/issues/new

## Requested feature

Please provide arm64 support for the getenvoy application.

**Comment by cetanu** [comment]
Linking #84 #82 

Pretty keen for this too

**Comment by cetanu** [comment]
If anyone knows how to run the pipeline for this project in order to produce an arm64 binary, or knows the barriers to doing so, I would be interested to hear them so that I can look into making it happen.

**Comment by cetanu** [comment]
Actually I was able to check out this repo and build it for arm64, but this is the repo for the `getenvoy` utility itself.

I think this is the more appropriate repo: https://github.com/tetratelabs/getenvoy-package

**Comment by lhaig** [comment]
Am happy to assist with creating a multi ARCH build script if this is what is needed. I use Consul in my demo's and it uses Envoy and I would like to have the ability to install and use it there if possible.

**Comment by codefromthecrypt** [comment]
one thing we'd need to do with this is understand the impact for testing. We are currently using GitHub Actions for testing via e2e, and I'm not sure if it supports linux/arm64 yet (In other projects I had to use travis to test this for real and when can't use emulation which isn't great)

**Comment by musaprg** [comment]
@codefromthecrypt Currently GitHub Actions(GHA) doesn't support linux/arm64 for now. One way is to prepare ARM instances on AWS as GHA self-hosted runner, and now I'm working on it.

**Comment by codefromthecrypt** [comment]
cool. some hint is you can still build for other archs with amd64 I've used this before https://github.com/multiarch/qemu-user-static then it reduces the complexity as one docker builder can build everything. you can even fake the arch to test, but it is also nice to use travis or a self-hosted GH action to really test in e2e, so what you are doing sounds good!

**Comment by codefromthecrypt** [comment]
@musaprg do we have any build of arm64 to try? the CLI can now support it.

**Comment by cetanu** [comment]
I managed to solve the problem of getting an ARM binary by extracting it from the container that Lyft builds:

```shell
docker pull envoyproxy/envoy:v1.16.3
containerid=`docker create envoyproxy/envoy:v1.16.3`
docker cp $containerid:/usr/local/bin/envoy ./
docker rm $containerid
```

**Comment by codefromthecrypt** [comment]
clever!

**Comment by codefromthecrypt** [comment]
if someone doesn't mind throwing up an ubuntu+arm64 (and ideally also macos) tar.gz or tar.xz of envoy in a public dir, that would be helpful. I'll pick up tomorrow and integrate the CLI then we'll only be awaiting some long term repo.

The archive needs a base dir, it can be anything, but `envoy-1.18.3` or similar would be fine. It needs to contain `envoy-1.18.3/bin/envoy` with execute bit.

**Comment by codefromthecrypt** [comment]
https://github.com/tetratelabs/getenvoy/pull/250 is only awaiting a public tarball

**Comment by codefromthecrypt** [comment]
@cetanu thanks for the tips. I can confirm that the latest binary will work on arm64. We still need to get a public URL for a real build, but luckily that can be done independent of binary changes. More details here https://github.com/codefromthecrypt/temprepo and this will stay open until we have a real tarball added to #250

**Comment by codefromthecrypt** [comment]
added this issue to ask envoy to retain the binaries they already build https://github.com/envoyproxy/envoy/issues/16830

**Comment by lhaig** [comment]
Thanks everyone I for one appreciate the efforts that are being done here.
Will there be an updated apt repo for the arm binaries?
I checked this morning again and there are only the AMD ones.

**Comment by codefromthecrypt** [comment]
@lhaig so we aren't building any new platforms as we are transitioning upstream builds. Can you please thumbsup this? envoyproxy/envoy#16830

Meanwhile, I've verified that recent releases of getenvoy work with the binaries upstream builds (I extracted via [docker](https://github.com/codefromthecrypt/temprepo))

```bash
export ENVOY_VERSIONS_URL=https://raw.githubusercontent.com/codefromthecrypt/temprepo/master/envoy-versions.json
getenvoy versions -a
```

As soon as there's a tarball published, we'll update the main json. I've been checking every day on this, and will definitely post back here immediately.
