### ISSUE TITLE
installing envoy in opensuse

### ISSUE THREAD

**Issue by nskalis** [tetratelabs/getenvoy#110]
**Describe the solution you'd like**
```
zypper addrepo https://getenvoy.io/linux/opensuse/tetrate-getenvoy.repo
zypper install getenvoy-envoy
```
or install via `rpm` for `openSUSE`.

**Describe alternatives you've considered**
running `envoy` as a container with `podman`, but I would rather avoid using containers

**Additional context**
The majority of software is available for installation for `openSUSE`, it would be great having the option to do so in case of the `envoy-proxy`. I am migrating away from CentOS to openSUSE.

**Comment by lizan** [comment]
Which openSUSE version are you using? I think the binary itself would work on openSUSE, so we just need to publish it as openSUSE repo.
