### ISSUE TITLE
Failing to install on Ubuntu 20.04.1 LTS

### ISSUE THREAD

**Issue by karlbateman** [tetratelabs/getenvoy#111]
**Describe the bug**

When following the [installation instructions](https://www.getenvoy.io/install/envoy/ubuntu/) for Ubuntu using apt, I receive the following GPG error after running `sudo add-apt-repository "deb [arch=amd64] https://dl.bintray.com/tetrate/getenvoy-deb $(lsb_release -cs) stable"`:

```
W: GPG error: https://dl.bintray.com/tetrate/getenvoy-deb focal Release: The following signatures were invalid: BADSIG 0253D0B26FF974DB GetEnvoy <getenvoy@tetrate.io>
E: The repository 'https://dl.bintray.com/tetrate/getenvoy-deb focal Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```

**To Reproduce**

Follow the [installation instructions](https://www.getenvoy.io/install/envoy/ubuntu/) on Ubuntu 20.04.1 LTS:

1. Run `sudo apt-get update`
2. Install dependencies `sudo apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common`
3. Add Tetrate GPG key `curl -sL 'https://getenvoy.io/gpg' | sudo apt-key add -`
4. Verify fingerprint `apt-key fingerprint 6FF974DB`.
5. Install apt repository `sudo add-apt-repository "deb [arch=amd64] https://dl.bintray.com/tetrate/getenvoy-deb $(lsb_release -cs) stable"`
6. Error (see details in description above)

**Expected behavior**

Envoy to install without issue.

**Screenshots**

Error received when adding the repository:

![Repository install error screenshot](https://i.ibb.co/wRjrmZV/Screenshot-from-2020-12-18-11-41-31.png)

GPG fingerprint verification:

![GPG fingerprint verification screenshot](https://i.ibb.co/sKjNm4q/Screenshot-from-2020-12-18-11-55-06.png)

**Environment (please complete the relevant information):**

 - OS: Ubuntu 20.04.1
 - Envoy Version: 1.16.2

**Additional context**

With the below added to a `Dockerfile` you can easily reproduce the issue by running `docker build --force-rm - < Dockerfile`.

```Dockerfile
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common \
    sudo \
    && rm -rf /var/lib/apt/lists/*

RUN curl -sL 'https://getenvoy.io/gpg' | apt-key add -
RUN add-apt-repository "deb [arch=amd64] https://dl.bintray.com/tetrate/getenvoy-deb $(lsb_release -cs) stable"
RUN apt-get update && sudo apt-get install -y getenvoy-envoy

ENTRYPOINT ["envoy"]
```

**EDIT** add `sudo` to Dockerfile

**Comment by musaprg** [comment]
@karlbateman Hi. I'm sorry, but I cannot reproduce the issue in my Docker environment with the given Dockerfile. Does it still exist even if you try the instructions again?

**Comment by karlbateman** [comment]
@musaprg Hey, spologies for the delayed response. Thanks for checking this, it seems to be resolved now. Not sure what's fixed it 🤔
