### ISSUE TITLE
Bintray is going away

### ISSUE THREAD

**Issue by dkrutsko** [tetratelabs/getenvoy#113]
According to [this blog post](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter), Bintray is being retired May 1st. I believe this project will be affected as some of your artifacts, like RPM, are being stored there.

**Comment by codefromthecrypt** [comment]
could this be handled by whatever is hosting https://getenvoy.io?

However redirects and forwarding works, we could push the manifest.json on release to a gh-pages branch, which could be cached or served one way or another from a getenvoy.io path?

**Comment by codefromthecrypt** [comment]
@lizan thoughts on this?

**Comment by DerekStrickland** [comment]
FWIW, bintray is undergoing a scheduled brownout right now, and thus the getenvoy CLI is failing.

**Comment by codefromthecrypt** [comment]
#170 will fix this on next release.

There is a hidden option that folks can use in a pinch meanwhile, but disclaimer this flag is internal and so don't rely on it being around: `getenvoy --manifest https://dl.getenvoy.io/public/raw/files/manifest.json fetch standard:1.17.1`

**Comment by oktocat** [comment]
it's a bit premature to close it, there's still work that needs to be done with CI and packaging.

**Comment by codefromthecrypt** [comment]
ok can you link issues to that so we know when to close it? (possibly with check boxes). As I understand it, the other steps won't effect this repository, but if any do, let's make that visible somehow.

**Comment by oktocat** [comment]
right, other issues will affect different repos like this one: https://github.com/tetratelabs/getenvoy-package/pull/105

**Comment by codefromthecrypt** [comment]
The current getenvoy CLI doesn't reference anything in bintray anymore, and envoy system packages will eventually move upstream. Folks who want to know about system packages can follow tetratelabs/getenvoy-package#110

The current CLI release was built with a simpler JSON format. The latest version is [v0.3.0](https://github.com/tetratelabs/getenvoy/releases/tag/v0.3.0) though as it is a big release probably a v0.3.1 will happen soon with feedback.

The canonical version list is here https://raw.githubusercontent.com/tetratelabs/getenvoy/master/site/envoy-versions.json
but directly referenced via redirect in the default of `ENVOY_VERSIONS_URL=https://getenvoy.io/envoy-versions.json`

This file will have latest patch of non EOL releases defined by upstream, and anything older is exception basis https://github.com/envoyproxy/envoy/blob/main/RELEASES.md#release-schedule

This URL can be overridden and we don't expect to make any breaking changes to [the format](https://raw.githubusercontent.com/tetratelabs/getenvoy/master/site/envoy_versions-schema.json) now.

Anyone who wants to own their own destiny, should host their own file as the download links are not permalinks. That or use envoy system packages pointed at stable repos.

Meanwhile we will do our best to make sure things work (limited to hosting issues or requests from the upstream envoy project)!
