### ISSUE TITLE
getenvoy extension run: print a message explaining why the command is still running for 10+ sec after `Ctrl + C` 

### ISSUE THREAD

**Issue by yskopets** [tetratelabs/getenvoy#118]
**Is your feature request related to a problem? Please describe.**

* At the moment, when a user want to stop `getenvoy extension run` he has to press `Ctrl + C`
* However, the command continues to run for another `10+ seconds` without any indication why

**Describe the solution you'd like**

* Print a message explaining why the command doesn't terminate immediately on `Ctrl + C`
* Give users a chance to terminate immediately by pressing `Ctrl + C` for the second time

**Describe alternatives you've considered**

* none

**Additional context**

* none

**Comment by codefromthecrypt** [comment]
obviated by #200
