### ISSUE TITLE
getenvoy.io timeout error

### ISSUE THREAD

**Issue by aoskotsky-amplify** [tetratelabs/getenvoy#134]
**Describe the bug**
`curl -L https://getenvoy.io/cli | bash -s -- -b /usr/local/bin` times out because `getenvoy.io` is not available

**To Reproduce**
1. Run curl -L https://getenvoy.io/cli | bash -s -- -b /usr/local/bin
2. Timeout error

**Expected behavior**
GetEnvoy is downloaded

**Environment (please complete the relevant information):**
 - MacOS

**Comment by lizan** [comment]
netlify was having issue, this is now fixed. https://www.netlifystatus.com/
