### ISSUE TITLE
Revise CI setup to do less redundant work

### ISSUE THREAD

**Issue by codefromthecrypt** [tetratelabs/getenvoy#143]
Right now, our test setup doesn't cache anything, which forces tasks to re-download dependencies and take longer to complete than they need to. Also, re-pushes don't cancel in-progress builds of the former commit on PR. This leads to overlapping and redundant jobs. The combination of these means longer run queues and more parallel jobs than helpful.

I'm not sure how well cancellation features work, but actions/cache@v2 is very commonly used to cache go and docker dependencies between runs.

**Comment by dchw** [comment]
Hi! I had a look around some of your other open issues, and I am willing to help with your builds/CI.

Looks like there is just some elbow grease needed in image optimization and the like. Also, I think I can improve your caching situation by using [Earthly](https://earthly.dev/). One advantage of Earthly over `actions/cache@v2` is that the cache can also be shared by local developers too, which can improve the local dev/test loop.

Disclaimer: I work for Earthly. But, not all the improvements or help would be dependent on our tool; I genuinely think we have something we could offer you here.

Willing to get started, if you are open to my contribution?

**Comment by codefromthecrypt** [comment]
Disclaimer: I'm pretty new to the projects here even if fairly prolific in this repo lately. Take my opinion as just that.

Thanks for reaching out @dchw! Personally, I'm intrigued and in concept like this better than bazel. I also like reproducibility and prefer something the build manages vs trying to emulate GH actions like https://github.com/nektos/act (though I might still try to use this anyway). Personally, I would like to get experience with earthly even if it turned out to be something needed to change later.

One glitch here is that it only recently and with heavy effort is somewhat like our other projects. To then move it to be unlike is not bad, as someone needs to progress. On the other hand, this repo isn't stable, yet and it has a lot of moving parts and adding something new to the build may distract from fixing the other things. In other words, to add another new thing here now, might not be the best timing.

I noticed https://github.com/tetratelabs/getenvoy-package is full of custom scripts and things, but seems like it doesn't need to. I can't speak for others, but you could check there and someone might answer. Meanwhile, if other maintainers are on board with trying here, I'd support it also, just above commentary in mind.

**Comment by dchw** [comment]
Makes sense. I get that it might be hard to move or introduce weirdness in a single repository without adopting it organization wide. Maybe, the best approach then is to give it a shot, but try to decouple enough benefit from our tool that its not a complete waste of time for you and your team? Though, I do also believe that Earthly could offer a lot based on what I have seen from snooping around.

**Comment by codefromthecrypt** [comment]
With expectations set as you mentioned, seems fair enough. Main thing about a tool is usually it needs a champion and if I switch projects it could be perceived a bomb if others aren't on board. Anyway, the best way forward is like you said imho. meta discussing < trying and deciding. If you are ok with a potential not-merge, please show us the way!

**Comment by codefromthecrypt** [comment]
there's little going on anymore as everything including e2e is 2m after #200
