### ISSUE TITLE
`getenvoy list` errors with 403 response

### ISSUE THREAD

**Issue by benfoxall** [tetratelabs/getenvoy#196]
**Describe the bug**

When I run `getenvoy list`, I see the following:

> Error: received 403 response code from https://tetrate.bintray.com/getenvoy/manifest.json

**To Reproduce**

1. Run `getenvoy list`
2. 👀 

**Expected behavior**

See a list of available Envoys

**Screenshots**

![image](https://user-images.githubusercontent.com/51385/116093993-0e02af80-a69f-11eb-99cc-8c784aa8de2b.png)

Additionally, requesting <https://tetrate.bintray.com/getenvoy/manifest.json> shows "Forbidden" for me.

![image](https://user-images.githubusercontent.com/51385/116094041-1bb83500-a69f-11eb-8f77-c37d899006b3.png)

**Environment (please complete the relevant information):**

 - OS: macOS
 - getenvoy: version 0.2.1-rc2

**Comment by cmayer-indeed** [comment]
It appears that Bintray is being sunset. https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by dekimsey** [comment]
It's not just listing. The bintray repository in it's entirety appears to be disabled/broken. _Packages_ haven't been published at the new hosting location on cloudsmith. The raw envoy binaries do at least appear to be available.

I found this while debugging why our RPM repositories syncs have started failing. I'm not sure if this is a misconfiguration or a prelude to the sunsetting (I have a guess ;)), but the getenvoy.io docs and urls haven't been updated to the new publishing locations which is definitely breaking things.

Access to the binaries appears to be available under dl.getenvoy.io and can be manually pulled like such:

```
$ curl -s https://dl.getenvoy.io/public/raw/files/manifest.json | jq '.flavors.standard.versions["1.18.2"]' | sed 's#https://dl.bintray.com/tetrate/getenvoy/#https://dl.getenvoy.io/public/raw/files/#g'
{
  "name": "1.18.2",
  "builds": {
    "LINUX_GLIBC": {
      "downloadLocationUrl": "https://dl.getenvoy.io/public/raw/files/getenvoy-envoy-1.18.2.p0.gd362e79-1p75.g76c310e-linux-glibc-release-x86_64.tar.xz",
      "platform": "LINUX_GLIBC"
    },
    "DARWIN": {
      "downloadLocationUrl": "https://dl.getenvoy.io/public/raw/files/getenvoy-envoy-1.18.2.p0.gd362e79-1p75.g76c310e-darwin-release-x86_64.tar.xz",
      "platform": "DARWIN"
    }
  }
}
```

I was able to reverse engineer the new repository paths by looking at #170 and the cloudsmith [repository](https://help.cloudsmith.io/docs/redhat-repository#setup) documentation. **Unfortunately, they contain no packages at this time.**

```
$ curl https://dl.getenvoy.io/public/cfg/setup/config.rpm.txt?distro=centos\&codename=7

# Source: Tetrate
# Repository: Tetrate / getenvoy
# Description: A certifiably-awesome public package repository curated by Tetrate, hosted by Cloudsmith.

[tetrate-getenvoy]
name=tetrate-getenvoy
baseurl=https://dl.getenvoy.io/public/rpm/el/7/$basearch
....
```

```
$ curl -s https://dl.getenvoy.io/public/rpm/el/7/x86_64/repodata/repomd.xml | grep primary.xml.gz
    <location href="repodata/0ba3a4a272278d3dcfc2acd950e2fe84-primary.xml.gz"/>
$ curl -s https://dl.getenvoy.io/public/rpm/el/7/x86_64/repodata/0ba3a4a272278d3dcfc2acd950e2fe84-primary.xml.gz | gunzip -c
<?xml version="1.0" encoding="UTF-8"?>
<metadata xmlns="http://linux.duke.edu/metadata/common" xmlns:rpm="http://linux.duke.edu/metadata/rpm" packages="0">
</metadata>
```

This appears to be the same problem reported in tetratelabs/getenvoy-package#106.

**Comment by lizan** [comment]
We're actively working on migrating off Bintray. They are doing another brownout and take the service down today. https://status.bintray.com/incidents/x1dvhtdqkcnx

**Comment by cmayer-indeed** [comment]
Do you think you'll have a resolution by the May 1 cutoff? I'm gauging whether a workaround is needed.

**Comment by oktocat** [comment]
FWIW jfrog went back on their original deadline and (although I haven't seen an official announcement) the deadline is 4th of July now. We will have a resolution before that, that's for sure.

**Comment by codefromthecrypt** [comment]
I think the workaround I mentioned [here](https://github.com/tetratelabs/getenvoy/issues/113#issuecomment-825262517) still works at least for list and get (using the undocumented `--manifest` flag) even if not everything works.

```bash
$ rm -rf ~/.getenvoy/builds/
$ getenvoy --manifest https://dl.getenvoy.io/public/raw/files/manifest.json run standard:1.17.1 -- --config-yaml 'admin: {"accessLogPath":"/dev/null","address":{"socketAddress":{"address":"127.0.0.1","portValue":15000}}}'
2021-04-30T00:50:08.731125Z	error	Log collection is not supported on this Operating System
fetching standard:1.17.1/darwin
[Fetching Envoy] 100% |████████████████████████████████████████|  [1s:0s] 
2021-04-30T00:50:16.333904Z	warn	Running on a non-Linux system, cannot set child process kill signal. Some cases where this process terminates before the Envoy child process may not be handled gracefully.
2021-04-30T00:50:16.334008Z	info	Envoy command: [/Users/adrian/.getenvoy/builds/standard/1.17.1/darwin/bin/envoy --config-yaml admin: {"accessLogPath":"/dev/null","address":{"socketAddress":{"address":"127.0.0.1","portValue":15000}}}]
```

Should we keep only one issue about bintray (#113) and link that to that until the packaging work is complete? That's been my strategy so far...

**Comment by codefromthecrypt** [comment]
To be clear, and I know this is confusing, the issue raised here is about getenvoy the tool not working, not about packages being available or not available.

We can probably keep those concerns split especially as there's nothing to change here about package anyway (that's tracked in getenvoy-package repo)

For now, until we have a release with a working manifest built by default, people can use the undocumented flag. I agree that there's no sense communicating a release until the packages are all resolved also. That's why #113 remains open.

**Comment by benfoxall** [comment]
I'm happy for this issue to be closed/resolved; `getenvoy list` is working again for me (at least until 4th of July 😅).    

Sounds like there's wider migration task, and it doesn't seem like keeping this issue open would be helpful for that.  Thanks for all the information!
