### ISSUE TITLE
command overhaul: 3 commands!

### ISSUE THREAD

**Issue by codefromthecrypt** [tetratelabs/getenvoy#248]
Hopefully, the last cleanup in pursuit of simplest path (before we release stuff!)

goals:
* intuitive as possible (little jargon)
* zero steps (no "run this before that")
* auto-completion friendly (avoid commands that share same first character)

end state:
* `getenvoy versions` (lists installed versions, -a includes remote ones not yet installed)
* `getenvoy use <version>` (assign current version, installing as necessary)
* `getenvoy run -c envoy.yaml` (run current version, installing as necessary)
current version is $ENVOY_VERSION, $PWD/.envoy-version or $ENVOY_HOME/version, which defaults to envoy-versions.json/latestVersion

current state (still not released):
* `run <version> -c envoy.yaml` (run installing on demand as necessary)
* `versions` (lists all versions)
* `install <version>` (install if not already)
* `installed` (lists all installed versions)
current version requires looking at the versions list

action 1: remove `<version>` from run, and read $ENVOY_VERSION $PWD/.envoy-version or $ENVOY_HOME/version
* simplifies `run` syntax and the need to know what version you'd want
* removes all questions about args to envoy: everything after `run` is interpreted by envoy
* $ENVOY_VERSION makes runs in CI for a non-latest version single-step
* on first run $ENVOY_HOME/version is populated from envoy-versions.json/latestVersion

action 2: repurpose `install -> use <version>`
* if we introduce a command to assign a version, there's a chance it isn't there, ends up the same as install
* rename install to use, and upon `use <version>` install it as necessary
* new change is to update $PWD/.envoy-version or $ENVOY_HOME/version if present

action 3: don't make a flag to write .envoy-version
* `getenvoy use 1.18.3 --local` is only 1 more char than `echo 1.18.3 > .envoy-version`
* by waiting to define a flag, we don't need to choose between bad jargon choices ex "local" or "cwd"
* by waiting, we can get more input from end users

action 4: fold `installed` into `versions -a/--all`
* `getenvoy install` collides on auto-complete with `getenvoy installed` which is annoying
* `getenvoy installed` output is different than `getenvoy versions` mainly because we didn't have release date locally
* during install, we can persist the "releaseDate" field into the $ENVOY_HOME/versions/$version directory create date
* at that point `getenvoy versions` shows the installed ones and `getenvoy versions -a` shows all including remote, both knowing the release date

**Comment by jcchavezs** [comment]
> removes all questions about args to envoy: everything after run is interpreted by envoy
 
 This is gold, I faced similar complexities when it comes to use protoc and abstractions like buf on top of it. You never know what options are interpreted by whom, ending up in a nightmare.
 
 > action 3: don't make a flag to write .envoy-version
 
 +1, let's don't rush on this. I know people usually don't like PHP but for example `composer` only has `--global` flag, everything else is local. I guess on lack of local you default to global.

**Comment by codefromthecrypt** [comment]
action 1: https://github.com/tetratelabs/getenvoy/pull/251

**Comment by codefromthecrypt** [comment]
action 4: https://github.com/tetratelabs/getenvoy/pull/252

**Comment by codefromthecrypt** [comment]
https://github.com/tetratelabs/getenvoy/pull/253 finishes this
