### ISSUE TITLE
Ability to download older versions of envoy

### ISSUE THREAD

**Issue by IceKickr** [tetratelabs/getenvoy#274]
**Is your feature request related to a problem? Please describe.**
Having trouble figuring out how to get version 1.16.3

**Describe the solution you'd like**
Ability to see all available versions. The only 1.16 version available in https://getenvoy.io/envoy-versions.json is:
    "1.16.4": {
      "releaseDate": "2021-05-11",
      "tarballs": {
        "darwin/amd64": "https://dl.getenvoy.io/public/raw/files/getenvoy-envoy-1.16.4.p0.gbf5d0eb-1p74.gbb8060d-darwin-release-x86_64.tar.xz",
        "linux/amd64": "https://dl.getenvoy.io/public/raw/files/getenvoy-envoy-1.16.4.p0.gbf5d0eb-1p74.gbb8060d-linux-glibc-release-x86_64.tar.xz"
      }
    },
1.16.3 might be still there, but I don't know the URL for it, and going to https://dl.getenvoy.io/public/raw/files/ gives a 404

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by codefromthecrypt** [comment]
we are trying not to add old versions by default in the new file format, but we still have a link to that, so will add it for you. Good luck in general upgrade wise and thanks for explaining your use case.

**Comment by codefromthecrypt** [comment]
```bash
$ getenvoy use 1.16.3
downloading https://dl.getenvoy.io/public/raw/files/getenvoy-envoy-1.16.3.p0.gc4b7ab8-1p74.gbb8060d-darwin-release-x86_64.tar.xz
$ getenvoy run --config-yaml "admin: {access_log_path: '/dev/stdout', address: {socket_address: {address: '127.0.0.1', port_value: 0}}}"
1.16.3 is already downloaded
starting: /Users/adrian/.getenvoy/versions/1.16.3/bin/envoy --config-yaml admin: {access_log_path: '/dev/stdout', address: {socket_address: {address: '127.0.0.1', port_value: 0}}} --admin-address-path /Users/adrian/.getenvoy/runs/1623289523508285000/admin-address.txt
[2021-06-10 09:45:24.432][9321780][info][main] [external/envoy/source/server/server.cc:305] initializing epoch 0 (base id=0, hot restart version=disabled)
--snip--
```

**Comment by IceKickr** [comment]
Thank you very much!!!
