### ISSUE TITLE
Collect status of network interfaces pre-termination

### ISSUE THREAD

**Issue by liamawhite** [tetratelabs/getenvoy#40]
This should be a [node level](https://github.com/tetratelabs/getenvoy/blob/master/pkg/binary/envoy/debug/node.go) collection. Output should look similar to (or the same as) `ifconfig`.
The aim is to keep external dependencies to a minimum, so [this library](https://godoc.org/github.com/shirou/gopsutil/net) should be used.

```sh
root@4f51979ee734:/# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.17.0.2  netmask 255.255.0.0  broadcast 172.17.255.255
        ether 02:42:ac:11:00:02  txqueuelen 0  (Ethernet)
        RX packets 12699  bytes 18362151 (18.3 MB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 6454  bytes 353781 (353.7 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

**Comment by ZackButcher** [comment]
If we use an SDK we need to be careful to make sure we fail gracefully if e.g. we don't have permissions to read the host level network config.

**Comment by liamawhite** [comment]
Yup. By design, any errors returned by these functions are logged by the framework and then it continues.
