### ISSUE TITLE
Bootstrap or generate configuration for front proxy as recommended in https://github.com/envoyproxy/envoy/pull/8001/files

### ISSUE THREAD

**Issue by dio** [tetratelabs/getenvoy#45]
**Is your feature request related to a problem? Please describe.**
Envoy is a production-ready edge proxy and performs well in that role, however,
the default settings are tailored for the service mesh use case, and some values
need to be adjusted when using Envoy as an edge proxy.

**Describe the solution you'd like**
Follow the suggestion in https://github.com/envoyproxy/envoy/pull/8001/files for front proxy.

**Describe alternatives you've considered**
Not yet but manually crafting configs as suggested in https://github.com/envoyproxy/envoy/pull/8001/files

**Additional context**
Envoy is a production-ready edge proxy, and performs well in that role, however,
the default settings are tailored for the service mesh use case and some values
need to be adjusted when using Envoy as an edge proxy.

**Comment by codefromthecrypt** [comment]
#202 should address this use case
