### ISSUE TITLE
In CLI, use flavor to infer correct bootstrap 

### ISSUE THREAD

**Issue by ZackButcher** [tetratelabs/getenvoy#57]
Overall goal is to minimize the amount of config (flags/args/files) that have to passed in to `getenvoy` in the happy path case. When we introduce an `istio` flavor to the `getenvoy` CLI soon, we wind up having a pretty redundant invocation:

```sh
getenvoy run istio:1.2.5 \
    --mode router \
    --bootstrap istio \
    --controlplaneAddress istio-pilot.istio-system:15010
```

IMO given the flavor `istio`, we should be able to infer `bootstrap=istio` and even default to `controlplaneAddress=istio-pilot.istio-system:15010`. Then the invocation for this default case simplifies to:

```
getenvoy run istio:1.2.5 --mode router
```

One step more generally, there's a lot of configuration we can infer if we just know which control plane the user is going to be using, including the actual Envoy build, the correct bootstrap config, the default control plane address, etc. If we do this solely based on Envoy flavors we lose this specialization if the control plane doesn't have any Envoy secret-sauce. So in this scheme for app mesh you'd still have the verbose invocation like:
```sh
getenvoy run standard:nightly \
    --mode router \
    --bootstrap appmesh \
    --controlplaneAddress app.mesh.aws
```

If we add smarts based on flavor, I wonder if it's not worth some effort to either make more flavors - not just for each individual build of Envoy but each use case, so we'd have flavors like `istio`, `appmesh`, `trafficdirector`, etc (even if two use cases both actually execute e.g. `standard:1.11.1` under the hood). This would make sense if we're doing stuff like packaging up bootstrap config with the binary that's being downloaded. Or, we could elevate each platform to a command in the CLI itself, so rather than `getenvoy run istio:1.2.5 --mode sidecar` we might say: `getenvoy run istio sidecar` (`getenvoy istio run sidecar --version 1.2.5` - however it winds up making sense logically), and similarly `getenvoy run appmesh`, and so on. This would default to the latest released version, the platforms bootstrap, the platforms default control plane address, etc. Any of them could be overridden per normal by just setting the flag, like you'd do today.

**Comment by codefromthecrypt** [comment]
istio bootstrap probably only worked 2 years ago and has crippled to project from a maintenance pov. #178 will remove it and obviate this
