### ISSUE TITLE
unable to bind domain socket with id=0 (see --base-id option)

### ISSUE THREAD

**Issue by soheilade** [tetratelabs/getenvoy#69]
Hey guys, 
running this command  `envoy -c basic-front-proxy.yaml` leads to this error.
`unable to bind domain socket with id=0 (see --base-id option)`
Is there a way to see all envoy containers? something like `docker ps -a`
I also need to execute a command in my envoy container that is created from `envoy -c basic-front-proxy.yaml` to see if my envoy can actually see(i.e, ping) another container. Any idea?

**Comment by soheilade** [comment]
my solution to work around this problem: 
`ps ax | grep envoy`
find the process id of the process the `envoy -c basic-front-proxy.yaml` command created and kill it.

**Comment by liamawhite** [comment]
Standard practice is to pick a random number for the `--base-id` flag. Our CLI will be doing this in the future.
