### ISSUE TITLE
How can I re-use this repo without calling the CLI?

### ISSUE THREAD

**Issue by frasercobb** [tetratelabs/getenvoy#74]
Hello,

Thanks for this tool, appreciate the work.

I would like to, using go, pull down a given version of envoy for a given OS. I initially attempted to use the packages used by the getenvoy CLI but there are a few implementation assumptions that prevent me from doing this. For example:

- I would need to create a `envoy.Runtime` struct to use the fetch method.
- Using the NewRuntime assumes the binaries will be stored in the users home dir.
- Assumes I am running as a CLI: e.g the progressbar in the `doDownload` function.
-  I can't use the options to override the default Runtime fields(e.g. the `fetcher.store`) as I cannot implement a pointer receiver functions outside of the package that creates that type.

**Options:**

1. Use`envoy.NewRuntime()` and set my home dir to a directory I choose. I still don't have control over the exact location, only the root. So the result will be: like `$HOMEDIR/.getenvoy/builds/$FLAVOUR/$VERSION/$PLATFORM`
2. Manually create the envoy.Runtime{} struct. However I cannot set the fetcher.store so the platformDirectory will return something like `/builds/$FLAVOUR/$VERSION/$PLATFORM`
3. Rely on the `manifest.DefaultURL` and implement the tarball extraction logic myself.

**Questions:**

1. Do you have any other options?
2. What would you recommend?

Thanks,
Fraser

**Comment by liamawhite** [comment]
Just to confirm, you basically want to use the runtime as a library? Whilst it's not really designed to be consumed as an external library it should be do-able. I will caveat this with saying in the future it's likely we are going to switch out the runner section mostly with Istio's `pilot-agent` plus a few customisations. The fetcher shouldn't change though

Feel free to create PR making the `Fetcher` and any other required variables mutable via a functional option. I think should meet your requirement?

**Comment by frasercobb** [comment]
Yes that's correct.
I only need the Fetcher logic so I'll see how I go and might create a PR if I get something worthwhile.
Thanks mate.
