### ISSUE TITLE
"Copy" on a multiline bash only copying the first line adding the stable repository

### ISSUE THREAD

**Issue by tevahp** [tetratelabs/getenvoy#75]
lkysowLuke Kysow@lkysow
3 days ago
@Tetrateio small issue on getenvoy.io (which is great btw). If you click "copy" on a multiline bash command you only get the first line.

(Adding the stable repository)

**Describe the bug**

**To Reproduce**
1. Run Envoy '...'
2. Make request '....'
3. See error

**Expected behavior**

**Screenshots**

**Environment (please complete the relevant information):**
 - OS: [e.g. Ubuntu 16:04]
 - Envoy Version: [e.g. 1.10.0]

**Additional context**

**Comment by liamawhite** [comment]
completed
