### ISSUE TITLE
getenvoy returning HTTP 401

### ISSUE THREAD

**Issue by uromahn** [tetratelabs/getenvoy#78]
**Describe the bug**
After installing getenvoy using the provided method, I am executing
`getenvoy list`
to list all available versions. However, I am receiving the following instead:
```
getenvoy list
Error: received 401 response code from https://tetrate.bintray.com/getenvoy/manifest.json
Usage:
  getenvoy list [flags]

Flags:
  -h, --help   help for list

received 401 response code from https://tetrate.bintray.com/getenvoy/manifest.json
```
I am receiving the same error when trying to install Envoy.

**To Reproduce**
1. Install `getenvoy` with the documented steps
2. Run `getenvoy list`
3. See `HTTP 401` error

**Expected behavior**
`getenvoy` should be able to complete all commands without 401 error code.

**Screenshots**
N/A

**Environment (please complete the relevant information):**
 - OS: CentOS 7
 - Getnvoy Version: 0.1.8

**Additional context**
N/A

**Comment by jhengy** [comment]
Thanks for the feedback, the issue should be resolved already

**Comment by uromahn** [comment]
Closing since the issue has been resolved - thanks!
