### ISSUE TITLE
Arm64 builds

### ISSUE THREAD

**Issue by beriberikix** [tetratelabs/getenvoy#82]
It would be very handy to have an Arm64 build, especially for use on a Raspberry Pi. The CNCF provides builds via https://cncf.ci/ that could used as a baseline.

**Comment by dkrutsko** [comment]
With the release of Amazon's [m6g](https://aws.amazon.com/blogs/aws/new-m6g-ec2-instances-powered-by-arm-based-aws-graviton2) instances, it would be really nice to have aarch64 builds available so we can take advantage of the cost savings without manually having to compile Envoy.

**Comment by lizan** [comment]
I'm going to work on this in next few weeks. Need to setup CI environment with AWS arm64 instances.

**Comment by morlay** [comment]
here a workflow for building envoy of istio.

https://github.com/querycap/istio-envoy-arm64

could merge it to here too?

**Comment by cageyv** [comment]
Amazon also release new [t4g](https://aws.amazon.com/ru/about-aws/whats-new/2020/09/announcing-new-amazon-ec2-t4g-instances-powered-by-aws-graviton2-processors/) instances. Graviton2 expansion:) I also think, that it would be really nice to have aarch64

**Comment by codefromthecrypt** [comment]
let's keep only one issue on arm64. I know this one came first, but #109 has more recent activity so closing in favor of that. please follow it and 👍 accordingly!
