### ISSUE TITLE
ARM32 builds

### ISSUE THREAD

**Issue by alam0rt** [tetratelabs/getenvoy#84]
People like myself use small SoCs to run and experiment with things like Kubernetes / Istio / etc. The trouble with running k8s on these arm boards is that more often than not, we need to compile everything for arm32. This is normally fine, but for someone like myself who isn't familiar with c++ cross compiliation, it is not as easy as I'd like.

I think providing arm32 binaries would be a boon to the arm/k8s community as it'd lower the entry requirements for running services such as Istio / Consul with sidecar proxies.

I am trying to build these binaries myself currently but am not totally confident that they will work as expected.

Thanks in advance.

`uname -a`
```
Linux node-3 4.14.150-odroidxu4 #2 SMP PREEMPT Mon Oct 28 08:07:45 CET 2019 armv7l GNU/Linux
```

**Comment by lizan** [comment]
related #82: there's upstream work ongoing to support ARM, primarily focusing on ARM64 though. Will see if we can get ARM32 build as well.

**Comment by rakyll** [comment]
+1. It would be great to have ARM support. ARM64 support seems to be complete: https://www.envoyproxy.io/docs/envoy/latest/start/building.html#arm64-binaries

**Comment by codefromthecrypt** [comment]
@alam0rt It has been a while (apologies) can you confirm that you still need arm32 and arm64 won't work for you? If so, we'll keep this open. Otherwise, we'll close it and focus on the other.

**Comment by codefromthecrypt** [comment]
closing in favor of arm64 until someone asks to re-open this
