### ISSUE TITLE
Local test environment using docker container.

### ISSUE THREAD

**Issue by musaprg** [tetratelabs/getenvoy#91]
**Is your feature request related to a problem? Please describe.**
Currently, we cannot test by default with Mac because of its security feature. It prevents envoy to run locally and tests fail while the confirmation dialog comes for envoy to use the internal network.

**Describe the solution you'd like**
For further convenience, it's better to add a docker environment for testing locally.
We can ensure the reliability of the test environment wherever we execute it.

**Comment by codefromthecrypt** [comment]
I currently run mac exclusively, and also added macos to the GH actions matrix. so I think we are ok now. Please re-open if not ok.
