### ISSUE TITLE
missing security / patch releases for v1.14.4, v1.13.4, v1.12.6 

### ISSUE THREAD

**Issue by desimone** [tetratelabs/getenvoy#94]
**Describe the bug**

There are no patch releases for v1.14.4, v1.13.4, and v1.12.6 despite being released the same day as v1.15.0 ;

I apologize if I missed any documentation stating your policy on back porting. 

**To Reproduce**

`getenvoy list`

**Expected behavior**

I would expect getenvoy to have releases for:

- v1.14.4,
- v1.13.4
-  v1.12.6

in addition to v1.15.0

**Screenshots**

**Environment (please complete the relevant information):**
 - OS: [e.g. Ubuntu 16:04] `Darwin Kernel Version 19.5.0`
 - Envoy Version: [e.g. 1.10.0] See above

**Additional context**

- https://groups.google.com/g/envoy-announce/c/yxFpI54NeWg
- https://github.com/pomerium/pomerium/pull/1076

**Comment by lizan** [comment]
Thanks for reporting, I will update it shortly.

**Comment by desimone** [comment]
@lizan looks fixed, thank you!
